// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file. Run `make proto` in examples/grpc to generate actual code.

package hellopb

// HelloRequest is the request message for SayHello
type HelloRequest struct {
	Name string
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// HelloReply is the response message for SayHello
type HelloReply struct {
	Message string
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Empty is an empty message
type Empty struct{}

// TimeReply is the response message for WatchTime
type TimeReply struct {
	Time string
}

func (x *TimeReply) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}
